[project]
name = "kubernetes-intro"
version = "0.1.0"
description = "A project to explain the basics of Kubernetes"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "manim>=0.19.0",
    "manim-slides[pyside6-full]>=5.4.2",
]
